# Generated by Django 5.1.3 on 2025-04-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=10)),
                ('gid_1', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('geometry', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.CharField(choices=[('tree', 'Tree'), ('bush', 'Bush')], max_length=50),
        ),
    ]
