# Generated by Django 5.1.3 on 2025-04-10 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_region_alter_species_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.region'),
        ),
    ]
