# Generated by Django 5.1.3 on 2025-04-10 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_plant_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='heat_index',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='planted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Seasonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.JSONField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.region')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.species')),
            ],
        ),
    ]
