# Generated by Django 5.1.3 on 2025-04-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_remove_region_heat_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='name',
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
