services:
  fruitsDataBase:
    image: postgres:latest
    container_name: fruitsDataBase
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5544:5432"
    volumes:
      - fruits_db_data:/var/lib/postgresql/data
      - ./init/:/docker-entrypoint-initdb.d/
    networks:
      - fruits_network
volumes:
  fruits_db_data:
networks:
  fruits_network:
    driver: bridge
